// Mock data for development — replace with real API/DB calls

export const mockSuppliers = [
  {
    id: "sup_001",
    name: "Kristinehamn Mekaniska AB",
    country: "SE",
    city: "Kristinehamn",
    region: "Värmland",
    tier: "REGIONAL",
    isHyperlocal: false,
    navalCertified: true,
    profileClaimed: true,
    founded: 1987,
    employees: 47,
    website: "www.kmab.se",
    description: "Precision machining specialist for marine and offshore industries. 5-axis CNC capability, duplex steel expertise.",
    capabilities: {
      processes: ["CNC 5-axis", "CNC Turning", "Grinding", "Assembly"],
      materials: ["Duplex", "316L Stainless", "Aluminium", "Bronze"],
      industries: ["Marine", "Offshore", "Energy"],
      tolerances: "±0.01mm standard, ±0.005mm special",
      batchMin: 1,
      batchMax: 500,
      leadTimeMin: 3,
      leadTimeMax: 8,
    },
    certifications: [
      { name: "ISO 9001:2015", verified: true, expiresAt: "2026-08-01" },
      { name: "DNV-GL", verified: true, expiresAt: "2025-12-01" },
      { name: "ISO 14001:2015", verified: true, expiresAt: "2026-08-01" },
    ],
    financial: {
      creditRating: "A",
      creditScore: 78,
      paymentScore: 94,
      revenue: 82000000,
      revenueCurrency: "SEK",
      revenueYear: 2024,
      ebit: 6800000,
      equityRatio: 42,
      ownershipType: "family",
      riskClass: "LOW",
      bankruptcyFlag: false,
      sanctionFlag: false,
      ubo: { name: "Svensson Family", country: "SE" },
    },
    capacity: {
      monthlyHours: 2400,
      currentLoad: 71,
      availableSlots: "~700 hours available Q4 2025",
    },
    esg: {
      co2ScopeOneTwo: 312,
      renewableEnergy: 78,
      iso14001: true,
      esgScore: 74,
    },
    qa: {
      deliveryPrecision: 94.2,
      nonConformance: 0.8,
      openDeviations: 1,
      overallScore: 87,
      lastAudit: "2024-11-15",
      lastAuditType: "REMOTE",
    },
    matchScore: 96,
  },
  {
    id: "sup_002",
    name: "PrecyzjaPlus Sp. z o.o.",
    country: "PL",
    city: "Gdańsk",
    region: "Pomerania",
    tier: "NATIONAL",
    isHyperlocal: false,
    navalCertified: true,
    profileClaimed: true,
    founded: 1995,
    employees: 120,
    website: "www.precyzjaplus.pl",
    description: "Large-scale precision machining. Marine class approved. Competitive pricing with strong quality track record.",
    capabilities: {
      processes: ["CNC 5-axis", "CNC Turning", "Milling", "Boring", "Honing"],
      materials: ["Duplex", "Carbon Steel", "Stainless", "Cast Iron"],
      industries: ["Marine", "Offshore", "Power Generation"],
      tolerances: "±0.01mm standard",
      batchMin: 10,
      batchMax: 2000,
      leadTimeMin: 4,
      leadTimeMax: 10,
    },
    certifications: [
      { name: "ISO 9001:2015", verified: true, expiresAt: "2026-03-01" },
      { name: "DNV-GL", verified: true, expiresAt: "2025-11-01" },
      { name: "Bureau Veritas", verified: true, expiresAt: "2025-09-01" },
    ],
    financial: {
      creditRating: "A-",
      creditScore: 74,
      paymentScore: 88,
      revenue: 48000000,
      revenueCurrency: "PLN",
      revenueYear: 2024,
      equityRatio: 38,
      ownershipType: "pe",
      riskClass: "LOW",
      bankruptcyFlag: false,
      sanctionFlag: false,
    },
    capacity: {
      monthlyHours: 5800,
      currentLoad: 65,
      availableSlots: "~2000 hours available",
    },
    esg: {
      co2ScopeOneTwo: 890,
      renewableEnergy: 45,
      iso14001: true,
      esgScore: 61,
    },
    qa: {
      deliveryPrecision: 91.8,
      nonConformance: 1.2,
      openDeviations: 3,
      overallScore: 82,
      lastAudit: "2024-09-20",
      lastAuditType: "ON_SITE",
    },
    matchScore: 88,
  },
  {
    id: "sup_003",
    name: "MachTech s.r.o.",
    country: "CZ",
    city: "Brno",
    region: "South Moravia",
    tier: "REGIONAL",
    isHyperlocal: false,
    navalCertified: false,
    profileClaimed: true,
    founded: 2003,
    employees: 68,
    website: "www.machtech.cz",
    description: "Precision components for industrial and energy applications. Competitive central European pricing.",
    capabilities: {
      processes: ["CNC 4-axis", "CNC Turning", "Grinding"],
      materials: ["Carbon Steel", "Stainless", "Aluminium"],
      industries: ["Energy", "Industrial", "Automotive"],
      tolerances: "±0.02mm standard",
      batchMin: 5,
      batchMax: 1000,
      leadTimeMin: 5,
      leadTimeMax: 12,
    },
    certifications: [
      { name: "ISO 9001:2015", verified: true, expiresAt: "2025-12-01" },
    ],
    financial: {
      creditRating: "BBB",
      creditScore: 61,
      paymentScore: 79,
      revenue: 28000000,
      revenueCurrency: "CZK",
      revenueYear: 2024,
      equityRatio: 31,
      ownershipType: "family",
      riskClass: "MEDIUM",
      bankruptcyFlag: false,
      sanctionFlag: false,
    },
    capacity: {
      monthlyHours: 3200,
      currentLoad: 82,
      availableSlots: "~580 hours available",
    },
    esg: {
      co2ScopeOneTwo: 520,
      renewableEnergy: 32,
      iso14001: false,
      esgScore: 44,
    },
    qa: {
      deliveryPrecision: 88.5,
      nonConformance: 2.1,
      openDeviations: 2,
      overallScore: 76,
      lastAudit: "2024-06-10",
      lastAuditType: "SELF_ASSESSMENT",
    },
    matchScore: 79,
  },
  {
    id: "sup_004",
    name: "Munkfors Svets & Mekan HB",
    country: "SE",
    city: "Munkfors",
    region: "Värmland",
    tier: "MICRO",
    isHyperlocal: true,
    navalCertified: false,
    profileClaimed: true,
    founded: 2008,
    employees: 6,
    website: "",
    description: "Local welding and light machining. Family-run workshop. Fast turnaround for smaller batches.",
    capabilities: {
      processes: ["MIG/MAG Welding", "TIG Welding", "Light Machining", "Fabrication"],
      materials: ["Carbon Steel", "Stainless"],
      industries: ["Industrial", "Agriculture", "Local"],
      tolerances: "±0.5mm",
      batchMin: 1,
      batchMax: 50,
      leadTimeMin: 1,
      leadTimeMax: 3,
    },
    certifications: [
      { name: "ISO 3834-2 Welding", verified: false, expiresAt: null },
    ],
    financial: {
      creditRating: "BB",
      creditScore: 52,
      paymentScore: 85,
      revenue: 3200000,
      revenueCurrency: "SEK",
      revenueYear: 2024,
      ownershipType: "family",
      riskClass: "MEDIUM",
      bankruptcyFlag: false,
      sanctionFlag: false,
    },
    capacity: {
      monthlyHours: 400,
      currentLoad: 40,
      availableSlots: "240 hours available immediately",
    },
    esg: {
      renewableEnergy: 90,
      iso14001: false,
      esgScore: 55,
    },
    qa: {
      deliveryPrecision: 96.0,
      nonConformance: 0.5,
      openDeviations: 0,
      overallScore: 72,
      lastAudit: null,
      lastAuditType: null,
    },
    matchScore: 71,
  },
];

export const mockResilienceAlerts = [
  {
    id: "alert_001",
    alertType: "CONCENTRATION_RISK",
    severity: "WARNING",
    title: "High concentration: Machining in Poland",
    description: "74% of your machining spend is sourced from Polish suppliers. Consider diversifying to reduce geopolitical exposure.",
    metric: { current: 74, threshold: 70, category: "Machining", country: "PL" },
    supplierId: null,
    resolved: false,
    createdAt: "2025-04-10",
  },
  {
    id: "alert_002",
    alertType: "FINANCIAL_DISTRESS",
    severity: "WARNING",
    title: "Financial score drop: Alconza Berango SL",
    description: "Credit score dropped 19 points in 90 days. Revenue down 23% YoY. Payment delays increasing. Pre-qualify backup supplier.",
    metric: { scoreNow: 59, scoreBefore: 78, drop: 19, days: 90 },
    supplierId: "sup_alconza",
    resolved: false,
    createdAt: "2025-04-08",
  },
  {
    id: "alert_003",
    alertType: "CERTIFICATION_EXPIRY",
    severity: "INFO",
    title: "DNV-GL certificate expiring: PrecyzjaPlus",
    description: "DNV-GL certification expires in 47 days (2025-11-01). Contact supplier to confirm renewal status.",
    metric: { daysLeft: 47, certName: "DNV-GL" },
    supplierId: "sup_002",
    resolved: false,
    createdAt: "2025-04-12",
  },
  {
    id: "alert_004",
    alertType: "GEOPOLITICAL_RISK",
    severity: "INFO",
    title: "Updated export restrictions: Belarus",
    description: "New EU trade restrictions effective. Review 2 suppliers with Belarus-linked entities in ownership structure.",
    metric: { country: "BY", suppliersAffected: 2, annualSpend: 1200000 },
    supplierId: null,
    resolved: false,
    createdAt: "2025-04-14",
  },
];

export const mockTcaComparison = [
  { supplierId: "sup_001", name: "Kristinehamn Mekaniska AB", country: "SE", listPrice: 850, freight: 18, customs: 0, inspection: 12, storage: 9, currencyRisk: 0, geopoliticalRisk: 0, tca: 889, currency: "SEK", riskClass: "LOW", score: 91 },
  { supplierId: "sup_002", name: "PrecyzjaPlus Sp. z o.o.", country: "PL", listPrice: 173, freight: 22, customs: 0, inspection: 8, storage: 11, currencyRisk: 4, geopoliticalRisk: 3, tca: 221, currency: "PLN", tcaSek: 891, riskClass: "LOW", score: 88 },
  { supplierId: "sup_003", name: "MachTech s.r.o.", country: "CZ", listPrice: 142, freight: 24, customs: 0, inspection: 8, storage: 14, currencyRisk: 5, geopoliticalRisk: 2, tca: 195, currency: "CZK", tcaSek: 912, riskClass: "MEDIUM", score: 82 },
];
